version: "3.8"

services:
  notifier:
    image: wadevs12/notifier
    container_name: notifier
    environment:
      SLACK_TOKEN: "SLACK_TOKEN"
    ports:
    - "8888:8888"
    volumes:
      - ./logs:/workspace/logs
    restart: always
