version: "3.8"

services:
  notifier:
    image: notifier
    build:
      context: .
    container_name: notifier
    environment:
      CRAWLING_PERIOD: 10
    ports:
    - "8888:8888"
    volumes:
      - ./logs:/workspace/logs
    restart: always
